# OpenTelemetry Collector Configuration for SigNoz (HTTP)
# Use this if gRPC port 4317 is not accessible

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed

  logging:
    verbosity: normal

  # SigNoz exporter via OTLP HTTP (instead of gRPC)
  otlphttp/signoz:
    endpoint: http://signoz-otel-collector.railway.internal:4318
    tls:
      insecure: true

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1888
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [pprof, zpages, health_check]
  
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp/signoz, debug]
    
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp/signoz, debug]

  telemetry:
    logs:
      level: info
    metrics:
      address: 0.0.0.0:8888

# NOTE: Using OTLP HTTP (port 4318) instead of gRPC (port 4317)
# This is more reliable in some network configurations

