# OpenTelemetry Collector Configuration for SigNoz Cloud
# Region: US
# Endpoint: ingest.us.signoz.cloud:443

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  # Debug exporter for troubleshooting
  debug:
    verbosity: detailed

  # Logging exporter for debugging
  logging:
    verbosity: normal

  # SigNoz Cloud exporter via OTLP
  otlp/signoz:
    endpoint: ingest.us.signoz.cloud:443
    headers:
      "signoz-access-token": "${SIGNOZ_ACCESS_TOKEN}"
    tls:
      insecure: false  # Use TLS for cloud

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024
  
  # Resource processor to add service metadata
  resource:
    attributes:
      - key: service.name
        value: advanced-messenger-service
        action: upsert
      - key: deployment.environment
        value: production
        action: upsert

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1888
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [pprof, zpages, health_check]
  
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [logging, otlp/signoz, debug]
    
    metrics:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [logging, otlp/signoz, debug]

  telemetry:
    logs:
      level: info
    metrics:
      address: 0.0.0.0:8888

# Configuration for SigNoz Cloud US Region
# Access Token: Set via SIGNOZ_ACCESS_TOKEN environment variable
# UI Access: https://app.signoz.io/

