# OpenTelemetry Collector Configuration for Railway with SigNoz
# This configuration sends traces and metrics to SigNoz instead of Jaeger

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  # Debug exporter for troubleshooting
  debug:
    verbosity: detailed

  # Logging exporter for debugging
  logging:
    verbosity: normal

  # SigNoz exporter via OTLP
  # SigNoz accepts both traces and metrics via OTLP
  otlp/signoz:
    endpoint: signoz.railway.internal:4317
    tls:
      insecure: true
    headers:
      # Add your SigNoz ingestion key if using SigNoz Cloud
      # "signoz-access-token": "your-token-here"

  # Optional: Keep Zipkin as backup
  zipkin:
    endpoint: "http://zipkin.railway.internal:9411/api/v2/spans"
    format: proto

  # Prometheus exporter (for Prometheus if you still want it)
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      collector: "otel"

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024
  
  # Resource processor to add service metadata
  resource:
    attributes:
      - key: service.name
        value: advanced-messenger-service
        action: upsert
      - key: deployment.environment
        value: production
        action: upsert

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1888
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [pprof, zpages, health_check]
  
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [logging, otlp/signoz, debug]
    
    metrics:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [logging, otlp/signoz, prometheus, debug]

  telemetry:
    logs:
      level: info
    metrics:
      address: 0.0.0.0:8888

# NOTES:
# 1. SigNoz accepts both traces AND metrics via OTLP
# 2. Default SigNoz OTLP receiver port is 4317 (gRPC) or 4318 (HTTP)
# 3. SigNoz UI is typically on port 3301
# 4. If using SigNoz Cloud, update endpoint to: ingest.{region}.signoz.cloud:443
#    and set tls.insecure: false

